# Generated by Django 3.2.8 on 2021-11-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_boulims_price_groceries_broulims_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceries',
            name='albertsons_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='groceries',
            name='broulims_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='groceries',
            name='walmart_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
